LIVE_MODEL = "models/gemini-3.1-flash-live-preview"
MODEL_PLANNER = "gemini-2.5-flash"
MODEL_WRITER = "gemini-2.5-flash"
MODEL_LITE = "gemini-2.5-flash-lite"
MODEL_LEGACY = "gemini-2.0-flash"

CHANNELS = 1
SEND_SAMPLE_RATE = 16000
RECEIVE_SAMPLE_RATE = 24000
CHUNK_SIZE = 1024

MAX_FIX_ATTEMPTS = 5
MAX_REPLAN_ATTEMPTS = 2
MAX_RETRIES = 3
DEFAULT_TIMEOUT = 30
BROWSER_IDLE_TTL = 300

IMG_MAX_WIDTH = 640
IMG_MAX_HEIGHT = 360
JPEG_QUALITY = 60

MEMORY_MAX_VALUE_LENGTH = 380
MEMORY_MAX_CHARS = 2200
